(() => {
  const APP_KEY='my-money-v3-state';
  const CONFIG_KEY='my-money-v3-config';
  const EXPENSE_API='https://script.google.com/macros/s/AKfycbwYwrj4EUYM-nUkMcoB9Wjn3gevhXCCg66EKTxrN4cQ2aJ684IWZUyi0bhfg2c0ftny/exec';
  const NAV=[['home','⌂','HOME'],['flow','↔','FLOW'],['income','＋','INCOME'],['seed','◎','SEED'],['more','•••','MORE']];
  const CATS=['가계쇼핑','취미·사치쇼핑','외식비','간식비','술자리','고정비','세금','병원','교통비','기타'];
  const PAYMENTS=['PayPay카드','라쿠텐카드','페이디카드','PayPay잔고','현금'];
  const $=(q,r=document)=>r.querySelector(q), $$=(q,r=document)=>[...r.querySelectorAll(q)];
  const num=v=>Number(v||0), safe=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const clone=x=>JSON.parse(JSON.stringify(x));
  const today=()=>new Date().toISOString().slice(0,10), thisMonth=()=>today().slice(0,7);
  const uid=(p='id')=>`${p}-${Date.now()}-${Math.random().toString(36).slice(2,7)}`;
  const monthOffset=(m,d)=>{const [y,mo]=m.split('-').map(Number),x=new Date(y,mo-1+d,1);return `${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,'0')}`};
  const fmt=(v,c='JPY')=>c==='JPY'?`¥${Math.round(num(v)).toLocaleString('ja-JP')}`:c==='KRW'?`₩${Math.round(num(v)).toLocaleString('ko-KR')}`:`$${num(v).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2})}`;
  const blankState=()=>({
    meta:{source:'empty',syncedAt:null},settings:{startMonth:'2026-09',startBalances:{JPY:0,KRW:0,USD:0}},flow:{},ledger:[],salaries:[],templates:[],projects:[],sessions:[],payouts:[],fx:[],settlements:[],fixedTemplates:[],cardAccounts:[],timers:{},seed:{planStart:'2027-01',targetCurrency:'KRW',longGoal:20000000,annualGoal:0,rows:[]}
  });
  let state=loadLocal()||blankState(),config=loadConfig(),screen='home',incomeTab='main',sideTab='work',flowTab='summary',selectedMonth=state.settings?.startMonth||thisMonth();
  let expense={month:'',rows:[],loading:false,error:'',loaded:false},syncBusy=false;

  function loadLocal(){try{return JSON.parse(localStorage.getItem(APP_KEY)||'null')}catch{return null}}
  function saveLocal(){localStorage.setItem(APP_KEY,JSON.stringify(state))}
  function loadConfig(){try{return JSON.parse(localStorage.getItem(CONFIG_KEY)||'{}')}catch{return {}}}
  function saveConfig(){localStorage.setItem(CONFIG_KEY,JSON.stringify(config))}
  function normalize(d){d=clone(d||{});d.meta||={source:'snapshot'};d.settings||={startMonth:'2026-09'};d.settings.startBalances||={JPY:0,KRW:0,USD:0};['flow','ledger','salaries','templates','projects','sessions','payouts','fx','settlements','fixedTemplates','cardAccounts'].forEach(k=>d[k]||=(k==='flow'?{}:[]));d.timers||={};d.seed||={planStart:'2027-01',targetCurrency:'KRW',longGoal:20000000,annualGoal:0,rows:[]};d.seed.rows||=[];return d}
  function importHash(){const h=location.hash.match(/(?:^#|&)snapshot=([^&]+)/);if(!h)return;try{const raw=decodeURIComponent(escape(atob(h[1].replace(/-/g,'+').replace(/_/g,'/'))));state=normalize(JSON.parse(raw));state.meta={source:'snapshot',syncedAt:new Date().toISOString()};saveLocal();selectedMonth=state.settings.startMonth||selectedMonth;history.replaceState(null,'',location.pathname+location.search)}catch(e){console.error(e)}}
  importHash();

  const apiReady=()=>Boolean(config.apiUrl&&config.apiToken);
  async function api(action,payload={}){const r=await fetch(config.apiUrl,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action,token:config.apiToken,payload})});const j=await r.json();if(!j.ok)throw new Error(j.error||'API 오류');return j.data}
  async function sync(){if(!apiReady()){toast('현재는 로컬 스냅샷 모드. MORE에서 Sheets API가 연결되면 실시간 동기화됩니다.');return}syncBusy=true;renderHeader();try{state=normalize(await api('bootstrap'));state.meta={source:'google-sheets',syncedAt:new Date().toISOString()};saveLocal();toast('Google Sheets 동기화 완료');await loadExpense(selectedMonth,true)}catch(e){toast('동기화 실패 · '+e.message)}finally{syncBusy=false;renderAll()}}

  async function expenseGet(action,params={}){const qs=new URLSearchParams({action,...params});const r=await fetch(`${EXPENSE_API}?${qs}`);if(!r.ok)throw new Error('지출 API '+r.status);return r.json()}
  async function expensePost(body){const r=await fetch(`${EXPENSE_API}?payload=${encodeURIComponent(JSON.stringify(body))}`);if(!r.ok)throw new Error('지출 저장 '+r.status);return r.json()}
  async function loadExpense(month,force=false){if(expense.loading||(!force&&expense.loaded&&expense.month===month))return;expense={month,rows:[],loading:true,error:'',loaded:false};renderFlow();try{const d=await expenseGet('getMonth',{month});expense.rows=(d.rows||[]).map((r,i)=>({rowIndex:r.rowIndex||r['행']||i+2,date:String(r['날짜']||r.date||'').slice(0,10),item:r['항목']||r.item||'',category:r['카테고리']||r.category||'기타',payment:r['결제수단']||r.payment||'현금',amount:num(r['금액']??r.amount),isBalance:r['잔고여부']===true||r['잔고여부']==='TRUE'||r.isBalance===true,memo:r['메모']||r.memo||'',spendType:r['집계구분']||r.spendType||'일반'}));expense.loaded=true}catch(e){expense.error=e.message}finally{expense.loading=false;renderFlow()}}

  function months(){const set=new Set([state.settings?.startMonth,thisMonth(),...Object.keys(state.flow||{}),...(state.seed?.rows||[]).map(x=>x.month),...(state.salaries||[]).map(x=>x.payMonth),...(state.payouts||[]).map(x=>x.payMonth)].filter(Boolean));let a=[...set].sort();if(!a.length)a=[thisMonth()];const start=a[0],end=a.at(-1);a=[];for(let m=start,n=0;m<=end&&n++<60;m=monthOffset(m,1))a.push(m);return a}
  function fxFor(m=selectedMonth){return [...(state.fx||[])].filter(x=>x.month<=m).sort((a,b)=>a.month.localeCompare(b.month)).at(-1)||{krwPer100Jpy:0,jpyPerUsd:0}}
  function toJpy(v,c,m=selectedMonth){const r=fxFor(m);if(c==='JPY')return num(v);if(c==='KRW'&&num(r.krwPer100Jpy))return num(v)/num(r.krwPer100Jpy)*100;if(c==='USD'&&num(r.jpyPerUsd))return num(v)*num(r.jpyPerUsd);return null}
  function eq(v,c,m=selectedMonth){if(c==='JPY')return'';const j=toJpy(v,c,m);return j==null?'환율 미등록':`≈ ${fmt(j,'JPY')} · 등록환율 기준`}
  function flow(c,m=selectedMonth){const r=state.flow?.[m]?.[c]||{};const x={start:num(r.start),main:num(r.main),side:num(r.side),otherIn:num(r.otherIn),card:num(r.card),fixed:num(r.fixed),otherOut:num(r.otherOut),settlement:num(r.settlement),fxIn:num(r.fxIn),fxOut:num(r.fxOut),adjust:num(r.adjust)};x.end='end'in r?num(r.end):x.start+x.main+x.side+x.otherIn-x.card-x.fixed-x.otherOut-x.settlement+x.fxIn-x.fxOut+x.adjust;return x}
  function salaryTotals(s){const earn=(s.items||[]).filter(x=>x.kind==='지급').reduce((a,b)=>a+num(b.amount),0),ded=(s.items||[]).filter(x=>x.kind==='공제').reduce((a,b)=>a+num(b.amount),0);return{earn,ded,net:earn-ded}}
  function project(id){return(state.projects||[]).find(x=>x.id===id)}
  function sessionValue(p,s){const h=num(s.minutes)/60,g=p?.model==='시급'?h*num(p.hourlyPay):num(s.pass)*num(p?.unitPay)+num(s.fail)*num(p?.failPay);return{gross:g,ded:g*num(p?.deductionRate),net:g*(1-num(p?.deductionRate))}}
  function workSummary(p,m=selectedMonth){const ss=(state.sessions||[]).filter(x=>x.projectId===p.id&&String(x.date).startsWith(m));let mins=0,gross=0,net=0,count=0;ss.forEach(s=>{const q=sessionValue(p,s);mins+=num(s.minutes);gross+=q.gross;net+=q.net;count+=num(s.pass)+num(s.fail)+num(s.hold)+num(s.excluded)});return{sessions:ss.length,mins,gross,net,count,hourly:mins?net/(mins/60):0}}
  function payoutSummary(p,m=selectedMonth){const q=(state.payouts||[]).filter(x=>x.projectId===p.id&&(x.workMonth===m||x.payMonth===m));return{expected:q.reduce((a,b)=>a+num(b.expected),0),actual:q.reduce((a,b)=>a+num(b.actual),0),count:q.length}}
  function ledgerRows(m=selectedMonth,c=null){return(state.ledger||[]).filter(x=>x.month===m&&(!c||x.currency===c)&&x.reflect!=='미반영')}

  function renderHeader(){const ms=months();$('#monthSelect').innerHTML=ms.map(m=>`<option ${m===selectedMonth?'selected':''}>${m}</option>`).join('');$('#syncButton').textContent=syncBusy?'…':state.meta?.source==='google-sheets'?'✓':'↻';$('#syncButton').title=state.meta?.source==='google-sheets'?'Sheets LIVE':state.meta?.source==='snapshot'?'실데이터 스냅샷':'데이터 미연결'}
  function navHtml(){return NAV.map(([id,ic,l])=>`<button class="nav-button ${screen===id?'active':''}" data-go="${id}"><span>${ic}</span>${l}</button>`).join('')}
  function renderNav(){$('#mobileNav').innerHTML=navHtml();$('#desktopNav').innerHTML=navHtml()}
  function sourceBanner(){const s=state.meta?.source;if(s==='google-sheets')return'<div class="source-banner live">● Google Sheets LIVE</div>';if(s==='snapshot')return'<div class="source-banner warn">● 실제 데이터 스냅샷 · 편집은 로컬 저장, Sheets 연결 후 실시간 전환</div>';return'<div class="source-banner warn">● 데이터 연결 전 · 가짜 숫자는 표시하지 않습니다.</div>'}

  function currencyCard(c,cls=''){const r=flow(c);let k=[];if(c==='JPY')k=[['시작',r.start],['본업',r.main],['부업',r.side],['총 유출',r.card+r.fixed+r.otherOut+r.settlement+r.fxOut]];if(c==='KRW')k=[['시작',r.start],['부업',r.side],['고정·지원',r.fixed+r.settlement],['환전 순이동',r.fxIn-r.fxOut]];if(c==='USD')k=[['시작',r.start],['부업',r.side],['환전 유출',r.fxOut],['보유',r.end]];return`<article class="card ${cls} currency-${c.toLowerCase()}"><div class="card-title"><div><p class="eyebrow">${c}</p><h3>${c==='JPY'?'일본 운용금':c==='KRW'?'한국 자금':'달러 자금'}</h3></div><span class="tag">${selectedMonth}</span></div><div class="amount">${fmt(r.end,c)}</div><div class="fx-note">${eq(r.end,c)||'기준통화'}</div><div class="kpi-grid">${k.map(([a,b])=>`<div class="kpi"><small>${a}</small><strong>${fmt(b,c)}</strong></div>`).join('')}</div></article>`}
  function renderHome(){const active=(state.settlements||[]).filter(x=>x.active),side=(state.projects||[]).filter(x=>x.active!==false).map(p=>({p,s:workSummary(p)})).filter(x=>x.s.sessions||x.s.net).sort((a,b)=>b.s.net-a.s.net).slice(0,3);const seedRows=state.seed?.rows||[],seedActual=seedRows.reduce((a,b)=>a+num(b.actual),0),goal=num(state.seed?.longGoal);$('#screen-home').innerHTML=`${sourceBanner()}<p class="eyebrow">CONTROL BOARD</p><h1 class="page-title">지금 돈의 흐름</h1><p class="page-copy">세 통화의 월말 FLOW와 지금 해야 할 행동만 먼저 봅니다.</p><div class="grid currency-grid">${currencyCard('JPY','dark')}${currencyCard('KRW','lime')}${currencyCard('USD')}</div><div class="section-head"><div><h2>이번 달 액션</h2></div></div><div class="grid two-col"><article class="card"><div class="card-title"><h3>부업 생산성</h3><button class="btn ghost small" data-open-side>SIDE</button></div>${side.length?side.map(({p,s})=>`<div class="line"><span><strong>${safe(p.name)}</strong><br><span class="muted">${(s.mins/60).toFixed(1)}h · ${s.sessions} sessions</span></span><span style="text-align:right"><strong>${fmt(s.net,p.currency)}</strong><br><span class="fx-note">${eq(s.net,p.currency)}</span></span></div>`).join(''):'<div class="empty">이 달의 작업 세션 없음</div>'}</article><article class="card"><div class="card-title"><h3>${active.length?'진행 중 정산':'SEED'}</h3><span class="tag ${active.length?'warn':'live'}">${active.length?'ACTIVE':'BUILD'}</span></div>${active.length?active.map(x=>`<div class="line"><span>${safe(x.title)}</span><strong>${fmt(x.current,x.currency)}</strong></div>`).join(''):`<div class="amount-sm">${fmt(seedActual,state.seed.targetCurrency)}</div><div class="muted">장기목표 ${fmt(goal,state.seed.targetCurrency)}</div><div class="progress" style="margin-top:12px"><i style="width:${goal?Math.min(100,seedActual/goal*100):0}%"></i></div>`}</article></div>`}

  function flowTabs(){return`<div class="subtabs"><button class="subtab ${flowTab==='summary'?'active':''}" data-flow-tab="summary">월간 FLOW</button><button class="subtab ${flowTab==='spend'?'active':''}" data-flow-tab="spend">지출</button><button class="subtab ${flowTab==='obligation'?'active':''}" data-flow-tab="obligation">카드·고정비</button></div>`}
  function flowSummary(){return`<div class="grid currency-grid">${['JPY','KRW','USD'].map(c=>{const r=flow(c),rows=[['시작잔고',r.start],['+ 본업',r.main],['+ 부업',r.side],['+ 기타수입',r.otherIn],['- 카드청구',-r.card],['- 계좌/현금 고정비',-r.fixed],['- 기타직접지출',-r.otherOut],['- 상환·지원금',-r.settlement],['+ 환전유입',r.fxIn],['- 환전유출',-r.fxOut],['± 잔고보정',r.adjust]];return`<article class="card"><div class="card-title"><div><p class="eyebrow">${c} FLOW</p><h3>${selectedMonth}</h3></div><strong class="amount-sm">${fmt(r.end,c)}</strong></div>${rows.filter(([n])=>!(c!=='JPY'&&n==='+ 본업')).map(([n,v])=>`<div class="line"><span>${n}</span><strong>${v<0?'−'+fmt(Math.abs(v),c):fmt(v,c)}</strong></div>`).join('')}<div class="summary-box"><div class="line"><span>FLOW 예상잔고</span><strong>${fmt(r.end,c)}</strong></div></div></article>`}).join('')}</div>`}
  function expenseStats(){const rows=expense.rows||[],sum=(f)=>rows.filter(f).reduce((a,b)=>a+num(b.amount),0);const byPay=Object.fromEntries(PAYMENTS.map(p=>[p,sum(x=>x.payment===p)])),byCat={};rows.forEach(x=>byCat[x.category]=(byCat[x.category]||0)+num(x.amount));const total=sum(()=>true),card=sum(x=>['PayPay카드','라쿠텐카드','페이디카드'].includes(x.payment)),balance=sum(x=>x.payment==='PayPay잔고'||x.isBalance),fixed=sum(x=>['고정비','세금'].includes(x.category));return{total,card,balance,fixed,byPay,byCat}}
  function renderSpend(){if(expense.month!==selectedMonth&&!expense.loading)loadExpense(selectedMonth);if(expense.loading)return'<div class="empty">지출 데이터 불러오는 중…</div>';if(expense.error)return`<div class="danger-note">지출 허브 연결 실패: ${safe(expense.error)}</div>`;const s=expenseStats(),max=Math.max(1,...Object.values(s.byCat));return`<div class="btn-row"><button class="btn" data-add-expense>＋ 지출</button><button class="btn ghost" data-batch-expense>여러건 입력</button><button class="btn ghost" data-csv-expense>CSV 가져오기</button></div><div class="metric-strip" style="margin-top:12px"><div class="metric-box"><small>상세 지출</small><strong>${fmt(s.total,'JPY')}</strong></div><div class="metric-box"><small>카드 사용</small><strong>${fmt(s.card,'JPY')}</strong></div><div class="metric-box"><small>잔고·현금</small><strong>${fmt(s.balance,'JPY')}</strong></div><div class="metric-box"><small>고정성</small><strong>${fmt(s.fixed,'JPY')}</strong></div></div><div class="section-head"><div><h2>결제수단</h2></div></div><div class="payment-grid">${PAYMENTS.map(p=>`<div class="pay-card"><small>${p}</small><strong>${fmt(s.byPay[p]||0,'JPY')}</strong></div>`).join('')}</div><div class="section-head"><div><h2>카테고리</h2></div></div><article class="card"><div class="cat-list">${Object.entries(s.byCat).sort((a,b)=>b[1]-a[1]).map(([c,v])=>`<div class="cat-row"><span>${safe(c)}</span><div class="cat-bar"><i style="width:${v/max*100}%"></i></div><strong>${fmt(v,'JPY')}</strong></div>`).join('')||'<div class="empty">이 달 상세지출 없음</div>'}</div></article><div class="section-head"><div><h2>내역</h2><p>가계부 데이터 허브의 실제 상세 내역</p></div></div><article class="card">${expense.rows.length?[...expense.rows].sort((a,b)=>String(b.date).localeCompare(String(a.date))).slice(0,80).map(x=>`<div class="expense-row"><div><h4>${safe(x.item)}</h4><p>${safe(x.date)} · ${safe(x.category)} · ${safe(x.payment)}${x.spendType==='할부·이월'?' · 할부/이월':''}</p></div><div class="right"><strong>${fmt(x.amount,'JPY')}</strong><small>${safe(x.memo)}</small></div></div>`).join(''):'<div class="empty">이 달 상세지출 없음</div>'}</article>`}
  function fixedRows(){return ledgerRows(selectedMonth).filter(x=>x.category==='고정비')}
  function cardDetail(){const s=expenseStats(),flowCard=flow('JPY').card,detail=s.byPay['PayPay카드']+s.byPay['라쿠텐카드']+s.byPay['페이디카드'];return{...s,flowCard,detail,diff:flowCard-detail}}
  function renderObligation(){const d=cardDetail(),fixed=fixedRows(),active=(state.settlements||[]).filter(x=>x.active);return`<div class="section-head"><div><h2>카드 청구</h2><p>FLOW 총액과 상세지출을 분리해서 봅니다.</p></div></div><div class="payment-grid"><div class="pay-card"><small>PayPay</small><strong>${fmt(d.byPay['PayPay카드']||0,'JPY')}</strong></div><div class="pay-card"><small>Rakuten</small><strong>${fmt(d.byPay['라쿠텐카드']||0,'JPY')}</strong></div><div class="pay-card"><small>Paidy</small><strong>${fmt(d.byPay['페이디카드']||0,'JPY')}</strong></div><div class="pay-card"><small>FLOW 카드청구</small><strong>${fmt(d.flowCard,'JPY')}</strong></div><div class="pay-card"><small>상세합계</small><strong>${fmt(d.detail,'JPY')}</strong></div></div>${Math.abs(d.diff)<1?'<div class="reconcile ok">✓ 카드 상세와 FLOW 카드청구가 맞습니다.</div>':`<div class="reconcile">상세와 FLOW 차이 ${fmt(d.diff,'JPY')} · 카드앱 명세/가계부 입력월 차이는 여기서 따로 보정하지 않고 차이로만 표시합니다.</div>`}<div class="section-head"><div><h2>고정비</h2><p>카드에 이미 포함된 고정비는 FLOW에서 이중차감하지 않습니다.</p></div><button class="btn ghost small" data-fixed-manage>템플릿</button></div><article class="card">${fixed.length?fixed.map(x=>`<div class="line"><span>${safe(x.item)}<br><span class="muted">${safe(x.currency)} · ${safe(x.status)}</span></span><strong>${fmt(x.amount,x.currency)}</strong></div>`).join(''):'<div class="empty">이 달 고정비 상세 없음</div>'}<div class="summary-box"><div class="line"><span>JPY FLOW 고정비</span><strong>${fmt(flow('JPY').fixed,'JPY')}</strong></div><div class="line"><span>KRW FLOW 고정비</span><strong>${fmt(flow('KRW').fixed,'KRW')}</strong></div></div></article><div class="section-head"><div><h2>정산·원금</h2><p>리보/지원금은 영구 네비가 아니라 진행 중일 때만 관리.</p></div></div><div class="obligation-grid">${active.length?active.map(x=>`<article class="obligation"><div class="head"><h3>${safe(x.title)}</h3><strong>${fmt(x.current,x.currency)}</strong></div><div class="meta">이번 계획 ${fmt(x.planned,x.currency)}</div><div class="progress" style="margin-top:10px"><i style="width:${x.current?Math.min(100,num(x.planned)/num(x.current)*100):0}%"></i></div></article>`).join(''):'<div class="empty">진행 중 정산 없음</div>'}</div>`}
  function renderFlow(){$('#screen-flow').innerHTML=`${sourceBanner()}<p class="eyebrow">FLOW</p><h1 class="page-title">${selectedMonth}</h1><p class="page-copy">거시 FLOW와 미시 지출을 한 화면 구조 안에서 분리해서 봅니다.</p>${flowTabs()}${flowTab==='summary'?flowSummary():flowTab==='spend'?renderSpend():renderObligation()}`}

  function renderIncome(){$('#screen-income').innerHTML=`${sourceBanner()}<p class="eyebrow">INCOME</p><h1 class="page-title">돈 만드는 쪽</h1><div class="pill-tabs"><button class="pill ${incomeTab==='main'?'active':''}" data-income-tab="main">MAIN · 본업</button><button class="pill ${incomeTab==='side'?'active':''}" data-income-tab="side">SIDE · 부업</button></div>${incomeTab==='main'?renderMain():renderSide()}`}
  function renderMain(){const a=[...(state.salaries||[])].sort((x,y)=>String(y.payDate).localeCompare(String(x.payDate)));return`<div class="btn-row"><button class="btn" data-new-salary="blank">＋ 신규</button><button class="btn ghost" data-new-salary="copy">⧉ 전월 급여 복사</button><button class="btn ghost" data-new-salary="template">▣ 템플릿에서 만들기</button></div><div class="section-head"><div><h2>급여 · 상여</h2><p>복사해서 숫자만 탭탭 수정하는 방식 유지.</p></div></div><div class="list">${a.length?a.map(salaryCard).join(''):'<div class="empty">본업 명세 없음</div>'}</div>`}
  function salaryCard(s){const t=salaryTotals(s),earn=(s.items||[]).filter(x=>x.kind==='지급').sort((a,b)=>num(a.order)-num(b.order)),ded=(s.items||[]).filter(x=>x.kind==='공제').sort((a,b)=>num(a.order)-num(b.order));const rows=(k,a)=>`<div class="section-head"><div><h2>${k} 항목</h2></div><button class="btn ghost small" data-add-salary-item="${safe(s.id)}" data-kind="${k}">＋ 항목</button></div><div class="editor-grid">${a.map(i=>`<div class="editor-row" data-salary-row data-id="${safe(s.id)}" data-kind="${k}" data-order="${i.order}"><input class="input" value="${safe(i.name)}" data-item-name><input class="input num" type="number" value="${num(i.amount)}" data-item-amount><button class="delete-x" data-remove-salary-item="${safe(s.id)}" data-kind="${k}" data-order="${i.order}">×</button></div>`).join('')}</div>`;return`<details class="list-item" data-salary="${safe(s.id)}"><summary class="list-main"><div><h3>${safe(s.type)} · ${safe(s.workMonth)}</h3><p>${safe(s.payDate)} 지급 · ${safe(s.status)}</p></div><div style="text-align:right"><strong>${fmt(t.net,'JPY')}</strong><div class="tag">NET</div></div></summary><div class="details"><div class="field-grid three"><div class="field"><label>유형</label><select class="select" data-salary-field="type"><option ${s.type==='급여'?'selected':''}>급여</option><option ${s.type==='상여'?'selected':''}>상여</option><option ${s.type==='기타 본업수입'?'selected':''}>기타 본업수입</option></select></div><div class="field"><label>작업월</label><input class="input" type="month" value="${safe(s.workMonth)}" data-salary-field="workMonth"></div><div class="field"><label>지급일</label><input class="input" type="date" value="${safe(s.payDate)}" data-salary-field="payDate"></div></div>${rows('지급',earn)}${rows('공제',ded)}<div class="summary-box"><div class="line"><span>총 지급</span><strong>${fmt(t.earn,'JPY')}</strong></div><div class="line"><span>공제</span><strong>${fmt(t.ded,'JPY')}</strong></div><div class="line"><span>실수령</span><strong>${fmt(t.net,'JPY')}</strong></div></div><div class="btn-row" style="margin-top:10px"><button class="btn lime" data-save-salary="${safe(s.id)}">저장</button><button class="btn ghost" data-copy-salary="${safe(s.id)}">이 명세 복사</button><button class="btn danger" data-delete-salary="${safe(s.id)}">삭제</button></div></div></details>`}

  function renderSide(){const ps=(state.projects||[]).filter(x=>x.active!==false);const all=ps.map(p=>({p,w:workSummary(p),q:payoutSummary(p)})),mins=all.reduce((a,b)=>a+b.w.mins,0),jobs=all.reduce((a,b)=>a+b.w.count,0),jpy=all.reduce((a,b)=>a+(toJpy(b.w.net,b.p.currency)||0),0),paid=all.reduce((a,b)=>a+(toJpy(b.q.actual,b.p.currency)||0),0);return`<div class="btn-row"><button class="btn" data-new-project>＋ 부업 추가</button><button class="btn ghost" data-oneoff>＋ 단발수입</button><button class="btn ghost" data-payout>＋ 입금 기록</button></div><div class="side-overview" style="margin-top:12px"><div class="side-kpi"><small>작업시간</small><strong>${(mins/60).toFixed(1)}h</strong></div><div class="side-kpi"><small>처리건수</small><strong>${jobs}</strong></div><div class="side-kpi"><small>작업가치 JPY환산</small><strong>${fmt(jpy,'JPY')}</strong></div><div class="side-kpi"><small>입금완료 JPY환산</small><strong>${fmt(paid,'JPY')}</strong></div></div><div class="workpay-toggle"><button class="pill ${sideTab==='work'?'active':''}" data-side-tab="work">WORK · 일한 달</button><button class="pill ${sideTab==='payout'?'active':''}" data-side-tab="payout">PAYOUT · 들어온 달</button></div>${sideTab==='work'?renderWork(ps):renderPayouts(ps)}`}
  function renderWork(ps){return`<div class="list">${ps.length?ps.map(p=>{const s=workSummary(p),ss=(state.sessions||[]).filter(x=>x.projectId===p.id&&String(x.date).startsWith(selectedMonth)).sort((a,b)=>String(b.date).localeCompare(String(a.date))).slice(0,8),timer=state.timers?.[p.id];return`<details class="list-item"><summary class="list-main"><div><h3>${safe(p.name)}</h3><p>${safe(p.platform)} · ${safe(p.model)} · ${p.currency}</p></div><div style="text-align:right"><strong>${fmt(s.net,p.currency)}</strong><div class="fx-note">${eq(s.net,p.currency)}</div></div></summary><div class="project-metrics"><div class="project-metric"><small>시간</small><strong>${(s.mins/60).toFixed(1)}h</strong></div><div class="project-metric"><small>세션/건수</small><strong>${s.sessions}/${s.count}</strong></div><div class="project-metric"><small>실효시급</small><strong>${fmt(s.hourly,p.currency)}</strong></div></div><div class="timer-row"><button class="btn ${timer?'timer-live':'ghost'} small" data-timer="${safe(p.id)}">${timer?'■ 타이머 종료':'▶ 타이머 시작'}</button><button class="btn ghost small" data-project-edit="${safe(p.id)}">프로젝트 설정</button></div><div class="session-box"><div class="field-grid three"><div class="field"><label>날짜</label><input class="input" type="date" value="${today()}" data-session-date></div><div class="field"><label>시작 · 10분</label><input class="input" type="time" step="600" value="10:10" data-session-start></div><div class="field"><label>종료 · 10분</label><input class="input" type="time" step="600" value="11:40" data-session-end></div>${p.model==='시급'?'':`<div class="field"><label>PASS</label><input class="input num" type="number" value="0" data-session-pass></div><div class="field"><label>FAIL</label><input class="input num" type="number" value="0" data-session-fail></div><div class="field"><label>HOLD</label><input class="input num" type="number" value="0" data-session-hold></div>`}</div><div class="session-total"><span>${p.model==='시급'?`시급 ${fmt(p.hourlyPay,p.currency)}`:`PASS ${fmt(p.unitPay,p.currency)} · FAIL ${fmt(p.failPay,p.currency)}`}</span><span>공제 ${(num(p.deductionRate)*100).toFixed(1)}%</span></div><button class="btn lime block" style="margin-top:10px" data-save-session="${safe(p.id)}">세션 저장</button></div><div class="section-head"><div><h2>최근 세션</h2></div></div>${ss.length?ss.map(x=>{const q=sessionValue(p,x);return`<div class="line"><span>${safe(x.date)} · ${(num(x.minutes)/60).toFixed(1)}h<br><span class="muted">P ${num(x.pass)} / F ${num(x.fail)} / H ${num(x.hold)}</span></span><span style="text-align:right"><strong>${fmt(q.net,p.currency)}</strong><br><span class="fx-note">${eq(q.net,p.currency,String(x.date).slice(0,7))}</span></span></div>`}).join(''):'<div class="empty">세션 없음</div>'}</details>`}).join(''):'<div class="empty">부업 프로젝트 없음</div>'}</div>`}
  function renderPayouts(ps){const a=[...(state.payouts||[])].filter(x=>x.payMonth===selectedMonth||x.workMonth===selectedMonth).sort((x,y)=>String(y.payDate).localeCompare(String(x.payDate)));return`<div class="section-head"><div><h2>WORK ↔ PAYOUT</h2><p>일한 달과 현금이 들어온 달을 절대 섞지 않습니다.</p></div></div><article class="card">${a.length?a.map(x=>{const p=project(x.projectId),v=num(x.actual)||num(x.expected);return`<div class="payout-row"><div><h4>${safe(p?.name||x.projectId)}</h4><p>작업 ${safe(x.workMonth)} → 입금 ${safe(x.payMonth)} · ${safe(x.status)}</p></div><div class="right"><strong>${fmt(v,x.currency)}</strong><div class="fx-note">${eq(v,x.currency,x.payMonth)}</div></div></div>`}).join(''):'<div class="empty">이 월 관련 입금기록 없음</div>'}</article>`}

  function renderSeed(){const s=state.seed||{},rows=s.rows||[],actual=rows.reduce((a,b)=>a+num(b.actual),0),goal=num(s.longGoal),actualStart=rows.find(x=>num(x.actual)>0)?.month||'—',year=selectedMonth.slice(0,4),yr=rows.filter(x=>x.month?.startsWith(year)),targetY=yr.reduce((a,b)=>a+num(b.target),0),actualY=yr.reduce((a,b)=>a+num(b.actual),0),delta=actualY-targetY;$('#screen-seed').innerHTML=`${sourceBanner()}<p class="eyebrow">SEED</p><h1 class="page-title">자본 만들기</h1><div class="grid two-col"><article class="card dark"><p class="eyebrow">LONG TERM</p><div class="amount">${fmt(actual,s.targetCurrency||'KRW')}</div><div class="muted">목표 ${fmt(goal,s.targetCurrency||'KRW')}</div><div class="progress" style="margin-top:12px"><i style="width:${goal?Math.min(100,actual/goal*100):0}%"></i></div><div class="line"><span>계획 시작</span><strong>${safe(s.planStart||'—')}</strong></div><div class="line"><span>실제 시작</span><strong>${safe(actualStart)}</strong></div></article><article class="card"><div class="field"><label>계획 시작월</label><input id="seedStart" class="input" type="month" value="${safe(s.planStart||'')}"></div><div class="field" style="margin-top:8px"><label>목표통화</label><select id="seedCur" class="select"><option ${s.targetCurrency==='KRW'?'selected':''}>KRW</option><option ${s.targetCurrency==='JPY'?'selected':''}>JPY</option><option ${s.targetCurrency==='USD'?'selected':''}>USD</option></select></div><div class="field" style="margin-top:8px"><label>장기목표</label><input id="seedGoal" class="input num" type="number" value="${num(goal)}"></div><button class="btn lime block" style="margin-top:9px" data-save-seed-config>목표 설정 저장</button></article></div><div class="section-head"><div><h2>${year} 월 목표 / 실제</h2><p class="seed-delta ${delta>=0?'good':'bad'}">현재 목표 대비 ${delta>=0?'+':''}${fmt(delta,s.targetCurrency||'KRW')}</p></div></div><div class="seed-months">${yr.map((x,i)=>`<div class="seed-month ${x.month<(s.planStart||'0000-00')&&!num(x.actual)?'inactive':''}"><div class="month-name">${x.month}</div><div class="field" style="margin-top:7px"><label>목표</label><input class="input num" type="number" value="${num(x.target)}" data-seed-target="${safe(x.month)}"></div><div class="field" style="margin-top:6px"><label>실제</label><input class="input num" type="number" value="${num(x.actual)}" data-seed-actual="${safe(x.month)}"></div></div>`).join('')||'<div class="empty">이 연도 SEED 행 없음</div>'}</div><article class="card chart-card"><canvas id="seedChart" width="900" height="230"></canvas></article>`;setTimeout(drawSeed,0)}
  function drawSeed(){const c=$('#seedChart');if(!c)return;const rows=(state.seed?.rows||[]).filter(x=>x.month?.startsWith(selectedMonth.slice(0,4))),q=c.getContext('2d'),w=c.width,h=c.height;let t=0,a=0,T=[],A=[];rows.forEach(x=>{t+=num(x.target);a+=num(x.actual);T.push(t);A.push(a)});const mx=Math.max(1,...T,...A);q.clearRect(0,0,w,h);const line=(v,col)=>{q.strokeStyle=col;q.lineWidth=5;q.beginPath();v.forEach((y,i)=>{const x=25+i*(w-50)/Math.max(1,v.length-1),yy=h-25-y/mx*(h-50);i?q.lineTo(x,yy):q.moveTo(x,yy)});q.stroke()};line(T,'#aab3bb');line(A,'#121c27')}

  function renderMore(){const fx=fxFor(),active=state.settlements||[];$('#screen-more').innerHTML=`${sourceBanner()}<p class="eyebrow">MORE</p><h1 class="page-title">정산 · 환율 · 설정</h1><div class="grid two-col"><article class="card"><div class="card-title"><h3>환율 등록</h3><span class="tag">${selectedMonth}</span></div><p class="page-copy">표시용 환율. 실제 환전은 FLOW의 환전유입/유출.</p><div class="field-grid"><div class="field"><label>¥100 = ₩</label><input id="fxKrw" class="input num" type="number" step=".01" value="${num(fx.krwPer100Jpy)||''}"></div><div class="field"><label>$1 = ¥</label><input id="fxUsd" class="input num" type="number" step=".01" value="${num(fx.jpyPerUsd)||''}"></div></div><button class="btn lime block" style="margin-top:9px" data-save-fx>이 달 환율 저장</button></article><article class="card"><div class="card-title"><h3>데이터 시작점</h3><span class="tag">ONE-TIME</span></div><div class="field"><label>운영 시작월</label><input id="startMonth" class="input" type="month" value="${safe(state.settings?.startMonth||'')}"></div><div class="field-grid three" style="margin-top:8px"><div class="field"><label>JPY 시작</label><input id="startJPY" class="input num" type="number" value="${num(state.settings?.startBalances?.JPY)}"></div><div class="field"><label>KRW 시작</label><input id="startKRW" class="input num" type="number" value="${num(state.settings?.startBalances?.KRW)}"></div><div class="field"><label>USD 시작</label><input id="startUSD" class="input num" type="number" step=".01" value="${num(state.settings?.startBalances?.USD)}"></div></div><button class="btn ghost block" style="margin-top:9px" data-save-start>시작점 저장</button></article></div><div class="section-head"><div><h2>정산</h2></div></div><div class="obligation-grid">${active.map(x=>`<article class="obligation"><div class="head"><h3>${safe(x.title)}</h3><strong>${fmt(x.current,x.currency)}</strong></div><div class="meta">이번 계획 ${fmt(x.planned,x.currency)} · ${x.active?'진행 중':'완료'}</div></article>`).join('')||'<div class="empty">정산 없음</div>'}</div><div class="section-head"><div><h2>템플릿</h2><p>급여·고정비는 신규/전월복사/템플릿을 공통 규칙으로 사용.</p></div><button class="btn ghost small" data-fixed-manage>고정비 템플릿</button></div><article class="card">${(state.templates||[]).map(t=>`<div class="line"><span>${safe(t.name)} · ${safe(t.area)}</span><strong>${safe(t.currency||'')}</strong></div>`).join('')||'<div class="empty">템플릿 없음</div>'}</article><div class="section-head"><div><h2>Google Sheets 연결</h2></div></div><article class="card"><div class="field"><label>Apps Script Web App URL</label><input id="apiUrl" class="input" value="${safe(config.apiUrl||'')}"></div><div class="field" style="margin-top:8px"><label>API Token</label><input id="apiToken" class="input" type="password" value="${safe(config.apiToken||'')}"></div><button class="btn block" style="margin-top:9px" data-save-api>연결 저장 & 동기화</button><p class="inline-note">토큰은 이 기기 브라우저에만 저장. GitHub에는 저장하지 않습니다.</p></article>`}

  function bind(){$$('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));$$('[data-flow-tab]').forEach(b=>b.onclick=()=>{flowTab=b.dataset.flowTab;renderFlow();bind()});$$('[data-income-tab]').forEach(b=>b.onclick=()=>{incomeTab=b.dataset.incomeTab;renderIncome();bind()});$$('[data-side-tab]').forEach(b=>b.onclick=()=>{sideTab=b.dataset.sideTab;renderIncome();bind()});$('[data-open-side]')?.addEventListener('click',()=>{incomeTab='side';go('income')});$('#monthSelect').onchange=e=>{selectedMonth=e.target.value;expense.loaded=false;renderAll();loadExpense(selectedMonth)};$('#syncButton').onclick=sync;$('#quickButton').onclick=openQuick;$('#sheetBackdrop').onclick=closeSheet;
    $$('[data-new-salary]').forEach(b=>b.onclick=()=>newSalary(b.dataset.newSalary));$$('[data-add-salary-item]').forEach(b=>b.onclick=()=>addSalaryItem(b.dataset.addSalaryItem,b.dataset.kind));$$('[data-remove-salary-item]').forEach(b=>b.onclick=()=>removeSalaryItem(b.dataset.removeSalaryItem,b.dataset.kind,num(b.dataset.order)));$$('[data-save-salary]').forEach(b=>b.onclick=()=>saveSalary(b.dataset.saveSalary));$$('[data-copy-salary]').forEach(b=>b.onclick=()=>copySalary(b.dataset.copySalary));$$('[data-delete-salary]').forEach(b=>b.onclick=()=>deleteSalary(b.dataset.deleteSalary));
    $$('[data-save-session]').forEach(b=>b.onclick=()=>saveSession(b.dataset.saveSession,b.closest('details')));$$('[data-timer]').forEach(b=>b.onclick=()=>toggleTimer(b.dataset.timer));$('[data-new-project]')?.addEventListener('click',openProject);$('[data-oneoff]')?.addEventListener('click',()=>openPayout(true));$('[data-payout]')?.addEventListener('click',()=>openPayout(false));$$('[data-project-edit]').forEach(b=>b.onclick=()=>openProject(b.dataset.projectEdit));
    $('[data-save-seed-config]')?.addEventListener('click',saveSeedConfig);$$('[data-seed-target]').forEach(i=>i.onchange=()=>saveSeedMonth(i.dataset.seedTarget,'target',num(i.value)));$$('[data-seed-actual]').forEach(i=>i.onchange=()=>saveSeedMonth(i.dataset.seedActual,'actual',num(i.value)));$('[data-save-fx]')?.addEventListener('click',saveFx);$('[data-save-start]')?.addEventListener('click',saveStart);$('[data-save-api]')?.addEventListener('click',saveApi);
    $('[data-add-expense]')?.addEventListener('click',openExpense);$('[data-batch-expense]')?.addEventListener('click',openBatchExpense);$('[data-csv-expense]')?.addEventListener('click',openCsvExpense);$('[data-fixed-manage]')?.addEventListener('click',openFixedTemplates)
  }
  function go(s){screen=s;$$('.screen').forEach(x=>x.classList.toggle('active',x.dataset.screen===s));renderAll();scrollTo({top:0,behavior:'smooth'})}
  function renderAll(){renderHeader();renderNav();renderHome();renderFlow();renderIncome();renderSeed();renderMore();bind()}

  function openSheet(html){$('#sheetContent').innerHTML=html;$('#sheet').classList.add('open');$('#sheet').setAttribute('aria-hidden','false')}
  function closeSheet(){$('#sheet').classList.remove('open');$('#sheet').setAttribute('aria-hidden','true')}
  function toast(t){const x=$('#toast');x.textContent=t;x.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>x.classList.remove('show'),2400)}
  function openQuick(){openSheet(`<h2 class="sheet-title">빠른 추가</h2><p class="sheet-copy">기록은 빠르게, 분석은 각 화면에서.</p><div class="quick-grid three"><button class="quick-card" data-q="expense"><strong>지출</strong><small>카드·잔고·현금</small></button><button class="quick-card" data-q="salary"><strong>본업</strong><small>급여/상여</small></button><button class="quick-card" data-q="session"><strong>부업 세션</strong><small>시간·건수</small></button><button class="quick-card" data-q="one"><strong>단발수입</strong><small>자유 금액</small></button><button class="quick-card" data-q="payout"><strong>입금 기록</strong><small>WORK→PAYOUT</small></button><button class="quick-card" data-q="seed"><strong>SEED</strong><small>목표/실제</small></button></div>`);$$('[data-q]').forEach(b=>b.onclick=()=>{closeSheet();const q=b.dataset.q;if(q==='expense'){flowTab='spend';go('flow');setTimeout(openExpense,50)}if(q==='salary'){incomeTab='main';go('income');setTimeout(()=>newSalary('copy'),50)}if(q==='session'){incomeTab='side';sideTab='work';go('income')}if(q==='one'){incomeTab='side';go('income');setTimeout(()=>openPayout(true),50)}if(q==='payout'){incomeTab='side';sideTab='payout';go('income');setTimeout(()=>openPayout(false),50)}if(q==='seed')go('seed')})}

  function newSalary(mode){let s={id:uid('salary'),payMonth:selectedMonth,workMonth:monthOffset(selectedMonth,-1),payDate:`${selectedMonth}-25`,type:'급여',status:'예정',templateId:'',items:[]};if(mode==='copy'&&state.salaries.length){const src=[...state.salaries].sort((a,b)=>String(b.payDate).localeCompare(String(a.payDate)))[0];s={...clone(src),id:uid('salary'),payMonth:selectedMonth,workMonth:monthOffset(selectedMonth,-1),payDate:`${selectedMonth}-25`,status:'예정'}}if(mode==='template'){const t=(state.templates||[]).find(x=>x.area==='MAIN');if(t){s.templateId=t.id;s.type=t.type||'급여';s.items=clone(t.items||[])}}state.salaries.unshift(s);saveLocal();incomeTab='main';renderIncome();bind();toast(mode==='copy'?'전월 명세 복사됨':'명세 생성됨')}
  function copySalary(id){const s=clone(state.salaries.find(x=>x.id===id));if(!s)return;s.id=uid('salary');s.payMonth=monthOffset(s.payMonth||selectedMonth,1);s.workMonth=monthOffset(s.workMonth||selectedMonth,1);s.payDate=`${s.payMonth}-25`;s.status='예정';state.salaries.unshift(s);saveLocal();renderIncome();bind()}
  function addSalaryItem(id,kind){const s=state.salaries.find(x=>x.id===id);s.items.push({kind,name:'새 항목',amount:0,order:Math.max(0,...s.items.map(x=>num(x.order)))+1});saveLocal();renderIncome();bind()}
  function removeSalaryItem(id,kind,order){const s=state.salaries.find(x=>x.id===id);s.items=s.items.filter(x=>!(x.kind===kind&&num(x.order)===order));saveLocal();renderIncome();bind()}
  async function saveSalary(id){const box=$(`[data-salary="${CSS.escape(id)}"]`),s=state.salaries.find(x=>x.id===id);if(!box||!s)return;s.type=$('[data-salary-field="type"]',box).value;s.workMonth=$('[data-salary-field="workMonth"]',box).value;s.payDate=$('[data-salary-field="payDate"]',box).value;s.payMonth=s.payDate.slice(0,7);$$('[data-salary-row]',box).forEach(r=>{const it=s.items.find(x=>x.kind===r.dataset.kind&&num(x.order)===num(r.dataset.order));if(it){it.name=$('[data-item-name]',r).value;it.amount=num($('[data-item-amount]',r).value)}});saveLocal();if(apiReady())try{await api('saveSalary',{salary:s});await sync();return}catch(e){toast('Sheets 저장 실패 · 로컬 유지')}renderIncome();bind();toast('저장됨')}
  async function deleteSalary(id){if(!confirm('이 명세 삭제?'))return;state.salaries=state.salaries.filter(x=>x.id!==id);saveLocal();if(apiReady())try{await api('deleteSalary',{id})}catch{}renderIncome();bind()}

  function timeMins(a,b){const x=a.split(':').map(Number),y=b.split(':').map(Number);let m=y[0]*60+y[1]-x[0]*60-x[1];return m<0?m+1440:m}
  async function saveSession(id,box){const p=project(id),s={id:uid('session'),projectId:id,date:$('[data-session-date]',box).value,start:$('[data-session-start]',box).value,end:$('[data-session-end]',box).value,pass:num($('[data-session-pass]',box)?.value),fail:num($('[data-session-fail]',box)?.value),hold:num($('[data-session-hold]',box)?.value),excluded:0};s.minutes=timeMins(s.start,s.end);state.sessions.push(s);saveLocal();if(apiReady())try{await api('appendSideSession',{session:s});await sync();return}catch(e){toast('Sheets 저장 실패 · 로컬 유지')}renderIncome();bind();const q=sessionValue(p,s);toast(`${(s.minutes/60).toFixed(1)}h · ${fmt(q.net,p.currency)}`)}
  function toggleTimer(id){state.timers||={};const t=state.timers[id];if(!t){state.timers[id]={startedAt:Date.now()};saveLocal();renderIncome();bind();toast('타이머 시작')}else{const d=new Date(t.startedAt),e=new Date(),round=x=>Math.round(x/10)*10,min=Math.max(10,round((e-d)/60000));state.sessions.push({id:uid('session'),projectId:id,date:today(),start:`${String(d.getHours()).padStart(2,'0')}:${String(round(d.getMinutes())%60).padStart(2,'0')}`,end:`${String(e.getHours()).padStart(2,'0')}:${String(round(e.getMinutes())%60).padStart(2,'0')}`,minutes:min,pass:0,fail:0,hold:0,excluded:0});delete state.timers[id];saveLocal();renderIncome();bind();toast(`타이머 ${min}분 저장`)}}
  function openProject(id){const p=id?clone(project(id)):{id:uid('project'),name:'',platform:'',model:'단발',currency:'JPY',unitPay:0,failPay:0,hourlyPay:0,deductionRate:0,active:true,note:''};openSheet(`<h2 class="sheet-title">부업 프로젝트</h2><div class="field"><label>이름</label><input id="pName" class="input" value="${safe(p.name)}"></div><div class="field" style="margin-top:8px"><label>플랫폼</label><input id="pPlatform" class="input" value="${safe(p.platform)}"></div><div class="field-grid" style="margin-top:8px"><div class="field"><label>수익모델</label><select id="pModel" class="select"><option ${p.model==='건당'?'selected':''}>건당</option><option ${p.model==='시급'?'selected':''}>시급</option><option ${p.model==='단발'?'selected':''}>단발</option><option ${p.model==='복합'?'selected':''}>복합</option></select></div><div class="field"><label>통화</label><select id="pCur" class="select"><option ${p.currency==='JPY'?'selected':''}>JPY</option><option ${p.currency==='KRW'?'selected':''}>KRW</option><option ${p.currency==='USD'?'selected':''}>USD</option></select></div></div><div class="field-grid three" style="margin-top:8px"><div class="field"><label>PASS/기본단가</label><input id="pUnit" class="input num" type="number" value="${num(p.unitPay)}"></div><div class="field"><label>FAIL단가</label><input id="pFail" class="input num" type="number" value="${num(p.failPay)}"></div><div class="field"><label>시급</label><input id="pHour" class="input num" type="number" value="${num(p.hourlyPay)}"></div></div><div class="field" style="margin-top:8px"><label>공제율 (예: 0.033)</label><input id="pDed" class="input num" type="number" step=".001" value="${num(p.deductionRate)}"></div><button id="saveProject" class="btn lime block" style="margin-top:12px">저장</button>`);$('#saveProject').onclick=async()=>{p.name=$('#pName').value;p.platform=$('#pPlatform').value;p.model=$('#pModel').value;p.currency=$('#pCur').value;p.unitPay=num($('#pUnit').value);p.failPay=num($('#pFail').value);p.hourlyPay=num($('#pHour').value);p.deductionRate=num($('#pDed').value);const i=state.projects.findIndex(x=>x.id===p.id);i<0?state.projects.push(p):state.projects[i]=p;saveLocal();if(apiReady())try{await api('upsertProject',{project:p})}catch{}closeSheet();renderIncome();bind()}}
  function openPayout(one){const ps=state.projects||[];openSheet(`<h2 class="sheet-title">${one?'단발수입':'입금 기록'}</h2><div class="field"><label>프로젝트</label><select id="poProject" class="select">${ps.map(p=>`<option value="${safe(p.id)}">${safe(p.name)}</option>`).join('')}</select></div><div class="field-grid" style="margin-top:8px"><div class="field"><label>작업월</label><input id="poWork" class="input" type="month" value="${selectedMonth}"></div><div class="field"><label>입금예정일</label><input id="poDate" class="input" type="date" value="${today()}"></div></div><div class="field-grid" style="margin-top:8px"><div class="field"><label>예상액</label><input id="poExpected" class="input num" type="number" value="0"></div><div class="field"><label>확정액</label><input id="poActual" class="input num" type="number" value="0"></div></div><div class="field"><label>메모</label><input id="poMemo" class="input"></div><button id="savePayout" class="btn lime block" style="margin-top:12px">저장</button>`);$('#savePayout').onclick=async()=>{const p=project($('#poProject').value),x={id:uid('payout'),projectId:p.id,workMonth:$('#poWork').value,payDate:$('#poDate').value,payMonth:$('#poDate').value.slice(0,7),currency:p.currency,expected:num($('#poExpected').value),actual:num($('#poActual').value),status:num($('#poActual').value)>0?'입금완료':'입금예정',memo:$('#poMemo').value};state.payouts.push(x);saveLocal();if(apiReady())try{await api('appendPayout',{payout:x,mirrorLedger:true})}catch{}closeSheet();renderIncome();bind()}}

  async function saveSeedConfig(){state.seed.planStart=$('#seedStart').value;state.seed.targetCurrency=$('#seedCur').value;state.seed.longGoal=num($('#seedGoal').value);saveLocal();if(apiReady())try{await api('saveSeedConfig',{seed:state.seed})}catch{}renderSeed();bind()}
  async function saveSeedMonth(m,k,v){let r=state.seed.rows.find(x=>x.month===m);if(!r){r={month:m,target:0,actual:0,note:''};state.seed.rows.push(r)}r[k]=v;saveLocal();if(apiReady())try{await api('saveSeedMonth',{row:r})}catch{}renderSeed();bind()}
  async function saveFx(){let r=state.fx.find(x=>x.month===selectedMonth);if(!r){r={id:'fx-'+selectedMonth,month:selectedMonth};state.fx.push(r)}r.krwPer100Jpy=num($('#fxKrw').value);r.jpyPerUsd=num($('#fxUsd').value);saveLocal();if(apiReady())try{await api('saveFx',{fx:r})}catch{}renderAll();toast('환율 저장')}
  function saveStart(){state.settings.startMonth=$('#startMonth').value;state.settings.startBalances={JPY:num($('#startJPY').value),KRW:num($('#startKRW').value),USD:num($('#startUSD').value)};saveLocal();renderAll();toast('시작점 저장')}
  async function saveApi(){config.apiUrl=$('#apiUrl').value.trim();config.apiToken=$('#apiToken').value.trim();saveConfig();toast('연결정보 저장');await sync()}

  function openExpense(){openSheet(`<h2 class="sheet-title">지출 추가</h2><div class="field-grid"><div class="field"><label>날짜</label><input id="eDate" class="input" type="date" value="${today()}"></div><div class="field"><label>금액</label><input id="eAmount" class="input num" type="number"></div></div><div class="field"><label>항목</label><input id="eItem" class="input"></div><div class="field-grid" style="margin-top:8px"><div class="field"><label>카테고리</label><select id="eCat" class="select">${CATS.map(x=>`<option>${x}</option>`).join('')}</select></div><div class="field"><label>결제수단</label><select id="ePay" class="select">${PAYMENTS.map(x=>`<option>${x}</option>`).join('')}</select></div></div><div class="field-grid" style="margin-top:8px"><div class="field"><label>집계구분</label><select id="eType" class="select"><option>일반</option><option>할부·이월</option></select></div><div class="field"><label>메모</label><input id="eMemo" class="input"></div></div><button id="saveExpense" class="btn lime block" style="margin-top:12px">저장</button>`);$('#saveExpense').onclick=async()=>{const entry={date:$('#eDate').value,item:$('#eItem').value,category:$('#eCat').value,payment:$('#ePay').value,amount:num($('#eAmount').value),isBalance:$('#ePay').value==='PayPay잔고',memo:$('#eMemo').value,spendType:$('#eType').value,'집계구분':$('#eType').value};if(!entry.date||!entry.item||!entry.amount)return toast('날짜·항목·금액 필요');try{await expensePost({action:'addEntry',month:selectedMonth,entry});closeSheet();await loadExpense(selectedMonth,true);toast('지출 저장')}catch(e){toast('지출 저장 실패')}}}
  function openBatchExpense(){openSheet(`<h2 class="sheet-title">여러건 입력</h2><p class="sheet-copy">한 줄씩: 9/4 라멘 1250 PayPay카드</p><textarea id="batchText" class="textarea" rows="9" placeholder="9/4 라멘 1250 PayPay카드\n9/4 편의점 680 PayPay잔고"></textarea><button id="saveBatch" class="btn lime block" style="margin-top:10px">파싱해서 저장</button>`);$('#saveBatch').onclick=async()=>{const lines=$('#batchText').value.split(/\n+/).map(x=>x.trim()).filter(Boolean),entries=[];for(const l of lines){const m=l.match(/^(\d{1,2})\/(\d{1,2})\s+(.+?)\s+(\d[\d,]*)\s+(PayPay카드|PayPay잔고|라쿠텐카드|페이디카드|현금)$/);if(!m)continue;entries.push({date:`${selectedMonth.slice(0,4)}-${String(m[1]).padStart(2,'0')}-${String(m[2]).padStart(2,'0')}`,item:m[3],category:'기타',payment:m[5],amount:num(m[4].replace(/,/g,'')),isBalance:m[5]==='PayPay잔고',memo:'',spendType:'일반','집계구분':'일반'})}if(!entries.length)return toast('파싱된 항목 없음');try{await expensePost({action:'bulkAdd',month:selectedMonth,entries});closeSheet();await loadExpense(selectedMonth,true);toast(`${entries.length}건 저장`)}catch(e){toast('저장 실패')}}}
  function openCsvExpense(){openSheet(`<h2 class="sheet-title">CSV 가져오기</h2><p class="sheet-copy">PayPay / Rakuten / Paidy / 가계부 CSV. 기존 가계부의 가져오기 흐름을 유지합니다.</p><input id="csvFile" class="input" type="file" accept=".csv"><div class="field" style="margin-top:8px"><label>타입</label><select id="csvType" class="select"><option value="custom">가계부CSV</option><option value="paypay">PayPay</option><option value="rakuten">Rakuten</option><option value="paidy">Paidy</option></select></div><button id="importCsv" class="btn lime block" style="margin-top:10px">읽어서 저장</button><p class="inline-note">카드사 CSV 열 구조가 바뀐 경우 미리보기 단계에서 패치합니다.</p>`);$('#importCsv').onclick=()=>{const f=$('#csvFile').files[0];if(!f)return toast('파일 선택');const rd=new FileReader();rd.onload=async()=>{const text=rd.result,lines=text.split(/\r?\n/).filter(Boolean),entries=[];if($('#csvType').value==='custom'){lines.slice(1).forEach(l=>{const cols=l.match(/("[^"]*"|[^,]+)/g)||[];const c=cols.map(x=>x.replace(/^"|"$/g,''));if(c.length>=7)entries.push({date:String(c[1]).slice(0,10),item:c[2],category:c[3]||'기타',payment:c[5]||'현금',amount:num(c[6]),isBalance:String(c[7]).toUpperCase()==='TRUE',memo:c[8]||'',spendType:c[4]||'일반','집계구분':c[4]||'일반'})} )}else{lines.forEach(l=>{const c=l.split(',').map(x=>x.replace(/^"|"$/g,'').trim());const amount=c.map(x=>Number(String(x).replace(/[¥￥,]/g,''))).find(x=>Number.isFinite(x)&&x>0);const date=c.find(x=>/^\d{4}[\/-]\d{1,2}[\/-]\d{1,2}/.test(x));if(date&&amount)entries.push({date:date.replace(/\//g,'-').slice(0,10),item:c.find(x=>x&&!/^\d/.test(x))||'CSV',category:'기타',payment:$('#csvType').value==='paypay'?'PayPay카드':$('#csvType').value==='rakuten'?'라쿠텐카드':'페이디카드',amount,isBalance:false,memo:'CSV',spendType:'일반','집계구분':'일반'})})}if(!entries.length)return toast('파싱 실패 · 샘플 CSV로 규칙 보정 필요');try{await expensePost({action:'bulkAdd',month:selectedMonth,entries});closeSheet();await loadExpense(selectedMonth,true);toast(`${entries.length}건 저장`)}catch(e){toast('CSV 저장 실패')}};rd.readAsText(f)} }
  function openFixedTemplates(){const list=state.fixedTemplates||[];openSheet(`<h2 class="sheet-title">고정비 템플릿</h2><p class="sheet-copy">새 월은 전월 복사 또는 이 템플릿 적용. 카드청구 포함 여부로 이중차감 방지.</p><div id="fixedList">${list.map((x,i)=>`<div class="fixed-row" data-fix="${i}"><input class="input" value="${safe(x.name)}" data-fn><input class="input num" type="number" value="${num(x.amount)}" data-fa><button class="delete-x" data-fdel="${i}">×</button></div>`).join('')}</div><div class="btn-row" style="margin-top:10px"><button class="btn ghost" id="addFix">＋ 항목</button><button class="btn lime" id="saveFix">템플릿 저장</button></div>`);$('#addFix').onclick=()=>{state.fixedTemplates.push({name:'새 고정비',amount:0,currency:'JPY',cashMode:'별도'});saveLocal();closeSheet();openFixedTemplates()};$$('[data-fdel]').forEach(b=>b.onclick=()=>{state.fixedTemplates.splice(num(b.dataset.fdel),1);saveLocal();closeSheet();openFixedTemplates()});$('#saveFix').onclick=()=>{$$('[data-fix]').forEach(r=>{const x=state.fixedTemplates[num(r.dataset.fix)];x.name=$('[data-fn]',r).value;x.amount=num($('[data-fa]',r).value)});saveLocal();closeSheet();toast('고정비 템플릿 저장')}}

  renderAll();loadExpense(selectedMonth);
})();