(() => {
  const M=window.MM,$=M.$,$$=M.$$,n=M.num;
  M.bind=()=>{
    $$('[data-go]').forEach(b=>b.onclick=()=>{M.screen=b.dataset.go;$$('.screen').forEach(x=>x.classList.toggle('active',x.dataset.screen===M.screen));M.renderAll()});
    $('#monthSelect').onchange=e=>{M.selectedMonth=e.target.value;M.renderAll()};
    $('#sheetBackdrop').onclick=M.closeSheet; $('#syncButton').onclick=()=>M.toast('현재 실제 데이터 스냅샷 사용 중');
    $('#quickButton').onclick=()=>{M.screen='flow';M.flowTab='big';$$('.screen').forEach(x=>x.classList.toggle('active',x.dataset.screen==='flow'));M.renderAll()};
    $$('[data-go-flow-big]').forEach(b=>b.onclick=()=>{M.screen='flow';M.flowTab='big';$$('.screen').forEach(x=>x.classList.toggle('active',x.dataset.screen==='flow'));M.renderAll()});
    $$('[data-flow-tab]').forEach(b=>b.onclick=()=>{M.flowTab=b.dataset.flowTab;M.renderFlow();M.bind()});
    $$('[data-del-big]').forEach(b=>b.onclick=()=>b.closest('[data-big-row]').remove());
    $('[data-add-big]')?.addEventListener('click',M.addBigRow);$('[data-save-big]')?.addEventListener('click',M.saveBig);$('[data-copy-big]')?.addEventListener('click',M.copyPrevBig);$('[data-apply-fixed]')?.addEventListener('click',M.applyFixed);
    $$('[data-income-tab]').forEach(b=>b.onclick=()=>{M.incomeTab=b.dataset.incomeTab;M.renderIncome();M.bind()});
    $$('[data-side-tab]').forEach(b=>b.onclick=()=>{M.sideTab=b.dataset.sideTab;M.renderIncome();M.bind()});
    $$('[data-new-salary]').forEach(b=>b.onclick=()=>M.newSalary(b.dataset.newSalary));$$('[data-copy-salary]').forEach(b=>b.onclick=()=>M.newSalary('copy',b.dataset.copySalary));$$('[data-save-salary]').forEach(b=>b.onclick=()=>M.saveSalary(b.dataset.saveSalary));$$('[data-delete-salary]').forEach(b=>b.onclick=()=>M.delSalary(b.dataset.deleteSalary));$$('[data-add-salary-item]').forEach(b=>b.onclick=()=>M.addSalaryItem(b.dataset.addSalaryItem,b.dataset.kind));$$('[data-remove-salary-item]').forEach(b=>b.onclick=()=>M.delSalaryItem(b.dataset.removeSalaryItem,b.dataset.kind,b.dataset.order));
    $('[data-add-project]')?.addEventListener('click',M.addProject);$$('[data-save-project]').forEach(b=>b.onclick=()=>M.saveProject(b.dataset.saveProject));$$('[data-delete-project]').forEach(b=>b.onclick=()=>M.deleteProject(b.dataset.deleteProject));$$('[data-timer]').forEach(b=>b.onclick=()=>M.toggleTimer(b.dataset.timer));
    $$('[data-save-session]').forEach(b=>b.onclick=()=>M.saveSession(b.dataset.saveSession));$$('[data-add-payout-project]').forEach(b=>b.onclick=()=>M.newPayout(b.dataset.addPayoutProject));$('[data-new-payout]')?.addEventListener('click',()=>M.newPayout());$$('[data-save-payout]').forEach(b=>b.onclick=()=>M.savePayout(b.dataset.savePayout));$$('[data-delete-payout]').forEach(b=>b.onclick=()=>M.deletePayout(b.dataset.deletePayout));
    $('[data-seed-start]')?.addEventListener('change',e=>{M.state.seed.planStart=e.target.value;M.save();M.renderSeed();M.bind()});$('[data-seed-goal]')?.addEventListener('change',e=>{M.state.seed.longGoal=n(e.target.value);M.save();M.renderSeed();M.bind()});$$('[data-seed-target]').forEach(x=>x.onchange=()=>{M.state.seed.rows[n(x.dataset.seedTarget)].target=n(x.value);M.save()});$$('[data-seed-actual]').forEach(x=>x.onchange=()=>{M.state.seed.rows[n(x.dataset.seedActual)].actual=n(x.value);M.save();M.renderSeed();M.bind()});
    $('[data-add-fx]')?.addEventListener('click',M.addFx);
    $('[data-edit-start]')?.addEventListener('click',()=>{M.openSheet(`<h2 class="sheet-title">시작점 편집</h2>${['JPY','KRW','USD'].map(c=>`<div class="field"><label>${c}</label><input class="input num" type="number" data-start-cur="${c}" value="${n(M.state.settings.startBalances[c])}"></div>`).join('')}<button id="startSave" class="btn lime block" style="margin-top:10px">저장</button>`);$('#startSave').onclick=()=>{['JPY','KRW','USD'].forEach(c=>M.state.settings.startBalances[c]=n($(`[data-start-cur="${c}"]`).value));M.save();M.closeSheet();M.renderAll();M.toast('시작점 저장')}});
    $('[data-add-card]')?.addEventListener('click',()=>{M.state.cardAccounts.push({id:M.uid('card'),name:'새 카드',currency:'JPY',active:true});M.save();M.renderMore();M.bind()});$$('[data-del-card]').forEach(b=>b.onclick=()=>{M.state.cardAccounts.splice(n(b.dataset.delCard),1);M.save();M.renderMore();M.bind()});$('[data-save-cards]')?.addEventListener('click',()=>{$$('[data-card-name]').forEach(x=>M.state.cardAccounts[n(x.dataset.cardName)].name=x.value);$$('[data-card-cur]').forEach(x=>M.state.cardAccounts[n(x.dataset.cardCur)].currency=x.value);M.save();M.toast('카드 설정 저장')});
    $('[data-add-fixed]')?.addEventListener('click',()=>{M.state.fixedTemplates.push({id:M.uid('fix'),name:'새 고정비',currency:'JPY',amount:0,active:true});M.save();M.renderMore();M.bind()});$$('[data-del-fixed]').forEach(b=>b.onclick=()=>{M.state.fixedTemplates.splice(n(b.dataset.delFixed),1);M.save();M.renderMore();M.bind()});$('[data-save-fixed]')?.addEventListener('click',()=>{$$('[data-fix-name]').forEach(x=>M.state.fixedTemplates[n(x.dataset.fixName)].name=x.value);$$('[data-fix-cur]').forEach(x=>M.state.fixedTemplates[n(x.dataset.fixCur)].currency=x.value);$$('[data-fix-amt]').forEach(x=>M.state.fixedTemplates[n(x.dataset.fixAmt)].amount=n(x.value));M.save();M.toast('고정비 템플릿 저장')});
    $('[data-save-settlement]')?.addEventListener('click',()=>{$$('[data-set-cur]').forEach(x=>M.state.settlements[n(x.dataset.setCur)].current=n(x.value));$$('[data-set-plan]').forEach(x=>M.state.settlements[n(x.dataset.setPlan)].planned=n(x.value));M.save();M.renderHome();M.toast('정산 저장')});
  };
  M.renderAll();
})();