const SHEETS={FLOW:'02 월간흐름',LEDGER:'03 입력원장',SETTLEMENT:'05 정산·잔액',PROJECTS:'06 부업프로젝트',SESSIONS:'07 부업세션',PAYOUTS:'08 부업정산',FX:'09 환율',SEED:'10 SEED',SALARY:'11 본업명세',TEMPLATES:'12 템플릿',ACTUAL:'13 현실잔고',CARDS:'14 카드·고정비'};
function setupMyMoney(spreadsheetId,apiToken){if(!spreadsheetId||!apiToken)throw new Error('spreadsheetId와 apiToken 필요');PropertiesService.getScriptProperties().setProperties({SPREADSHEET_ID:spreadsheetId,API_TOKEN:apiToken});return'OK'}
function doGet(){return json_({ok:true,data:{service:'MY MONEY V2 API',status:'ready',version:'v2-state-1'}})}
function doPost(e){try{const req=JSON.parse(e&&e.postData&&e.postData.contents||'{}');auth_(req.token);let data;if(req.action==='bootstrap')data=bootstrap_();else if(req.action==='saveAll')data=saveAll_(req.payload&&req.payload.state);else if(req.action==='saveActualBalance')data=saveActualBalance_(req.payload);else throw new Error('지원하지 않는 action: '+req.action);return json_({ok:true,data})}catch(err){return json_({ok:false,error:String(err&&err.message||err)})}}
function json_(x){return ContentService.createTextOutput(JSON.stringify(x)).setMimeType(ContentService.MimeType.JSON)}
function auth_(token){const x=PropertiesService.getScriptProperties().getProperty('API_TOKEN');if(!x||token!==x)throw new Error('Unauthorized')}
function ss_(){const id=PropertiesService.getScriptProperties().getProperty('SPREADSHEET_ID');if(!id)throw new Error('SPREADSHEET_ID 미설정');return SpreadsheetApp.openById(id)}
function sh_(n){const s=ss_().getSheetByName(n);if(!s)throw new Error('시트 없음: '+n);return s}
function vals_(n){return sh_(n).getDataRange().getValues()}
function n_(v){return typeof v==='number'?v:Number(String(v==null?'':v).replace(/,/g,''))||0}
function s_(v){if(v instanceof Date)return Utilities.formatDate(v,Session.getScriptTimeZone()||'Asia/Tokyo','yyyy-MM-dd');return v==null?'':String(v)}
function month_(v){const x=s_(v);return x.length>=7?x.slice(0,7):x}
function country_(cur){return cur==='JPY'?'JP':cur==='KRW'?'KR':'US'}
function clearBody_(sheet,row,colCount){const last=sheet.getLastRow();if(last>=row)sheet.getRange(row,1,last-row+1,colCount).clearContent()}
function setRows_(sheet,start,cols,rows){clearBody_(sheet,start,cols);if(rows.length)sheet.getRange(start,1,rows.length,cols).setValues(rows)}
function bootstrap_(){const flow=readFlow_(),settings=readStart_(flow),cf=readCardsFixed_();return{meta:{source:'google-sheet',syncedAt:new Date().toISOString()},settings,flow,ledger:readLedger_(),salaries:readSalaries_(),templates:readTemplates_(),projects:readProjects_(),sessions:readSessions_(),payouts:readPayouts_(),fx:readFx_(),settlements:readSettlements_(),fixedTemplates:cf.fixedTemplates,cardAccounts:cf.cardAccounts,actualBalances:readActual_(),timers:{},seed:readSeed_()}}
function readFlow_(){const v=vals_(SHEETS.FLOW),out={};for(let r=6;r<v.length;r++){const x=v[r],m=month_(x[0]),c=s_(x[1]);if(!m||!c)continue;(out[m]||={})[c]={start:n_(x[2]),main:n_(x[3]),side:n_(x[4]),otherIn:n_(x[5]),card:n_(x[6]),fixed:n_(x[7]),otherOut:n_(x[8]),settlement:n_(x[9]),fxIn:n_(x[10]),fxOut:n_(x[11]),adjust:n_(x[12]),end:n_(x[13])}}return out}
function readStart_(flow){const months=Object.keys(flow).sort(),startMonth=months[0]||'2026-09',startBalances={JPY:0,KRW:0,USD:0};['JPY','KRW','USD'].forEach(c=>startBalances[c]=n_(flow[startMonth]&&flow[startMonth][c]&&flow[startMonth][c].start));return{startMonth,startBalances}}
function readLedger_(){const v=vals_(SHEETS.LEDGER),out=[];for(let r=4;r<v.length;r++){const x=v[r];if(!x[0]&&!x[4])continue;out.push({month:month_(x[0]),date:s_(x[1]),currency:s_(x[2]),category:s_(x[3]),item:s_(x[4]),amount:n_(x[5]),reflect:s_(x[6])||'반영',status:s_(x[7])||'예정',workMonth:month_(x[8]),payMonth:month_(x[9]),linkId:s_(x[10]),memo:s_(x[11]),cashMode:s_(x[12]),settlementTarget:s_(x[13])})}return out}
function readProjects_(){const v=vals_(SHEETS.PROJECTS),out=[];for(let r=1;r<v.length;r++){const x=v[r];if(!x[0])continue;out.push({id:s_(x[0]),name:s_(x[1]),platform:s_(x[2]),model:s_(x[3]),currency:s_(x[4]),unitPay:n_(x[5]),failPay:n_(x[6]),hourlyPay:n_(x[7]),deductionRate:n_(x[8]),active:s_(x[9])!=='종료',delayDays:n_(x[10]),note:s_(x[11])})}return out}
function readSessions_(){const v=vals_(SHEETS.SESSIONS),out=[];for(let r=1;r<v.length;r++){const x=v[r];if(!x[0])continue;out.push({id:s_(x[0]),date:s_(x[1]),projectId:s_(x[2]),start:s_(x[3]),end:s_(x[4]),minutes:Math.round(n_(x[5])*60),pass:n_(x[6]),fail:n_(x[7]),hold:n_(x[8]),excluded:n_(x[9]),gross:n_(x[11]),deduction:n_(x[12]),net:n_(x[13]),currency:s_(x[14]),jpy:n_(x[15]),rateId:s_(x[16]),note:s_(x[17])})}return out}
function readPayouts_(){const v=vals_(SHEETS.PAYOUTS),out=[];for(let r=1;r<v.length;r++){const x=v[r];if(!x[0])continue;out.push({id:s_(x[0]),projectId:s_(x[1]),workMonth:month_(x[2]),payDate:s_(x[3]),payMonth:month_(x[4]),currency:s_(x[5]),expected:n_(x[6]),actual:n_(x[7]),status:s_(x[8]),ledgerId:s_(x[9]),jpy:n_(x[10]),memo:s_(x[11])})}return out}
function readFx_(){const v=vals_(SHEETS.FX),map={};for(let r=1;r<v.length;r++){const x=v[r],m=month_(x[1]);if(!m)continue;map[m]||={id:'fx-'+m,month:m,krwPer100Jpy:0,jpyPerUsd:0,note:''};const f=s_(x[2]),t=s_(x[3]),b=n_(x[4]),rate=n_(x[5]);if(f==='JPY'&&t==='KRW'&&b===100)map[m].krwPer100Jpy=rate;if(f==='USD'&&t==='JPY'&&b===1)map[m].jpyPerUsd=rate;map[m].note=s_(x[8])}return Object.keys(map).sort().map(k=>map[k])}
function readSalaries_(){const v=vals_(SHEETS.SALARY),map={};for(let r=1;r<v.length;r++){const x=v[r];if(!x[0])continue;const id=s_(x[0]);map[id]||={id,payMonth:month_(x[1]),workMonth:month_(x[2]),payDate:s_(x[3]),type:s_(x[4]),status:s_(x[10])||'예정',templateId:s_(x[9]),ledgerId:s_(x[11]),memo:s_(x[12]),items:[]};map[id].items.push({kind:s_(x[5]),name:s_(x[6]),amount:n_(x[7]),order:n_(x[8])})}return Object.values(map)}
function readTemplates_(){const v=vals_(SHEETS.TEMPLATES),map={};for(let r=1;r<v.length;r++){const x=v[r];if(!x[0])continue;const id=s_(x[0]);map[id]||={id,area:s_(x[1]),name:s_(x[2]),currency:s_(x[3]),type:s_(x[4]),active:s_(x[9])!=='종료',note:s_(x[11]),items:[]};map[id].items.push({kind:s_(x[5]),name:s_(x[6]),amount:n_(x[7]),order:n_(x[10])})}return Object.values(map)}
function readSettlements_(){const v=sh_(SHEETS.SETTLEMENT).getRange('A6:H11').getValues();return[{id:'japan-revo',title:'일본 리보',currency:'JPY',current:n_(v[1][1]),planned:n_(v[2][1]),active:n_(v[1][1])>0},{id:'korea-support',title:'한국 지원 잔액',currency:'KRW',current:n_(v[1][7]),planned:n_(v[2][7]),active:n_(v[1][7])>0}]}
function readActual_(){const v=vals_(SHEETS.ACTUAL),out={};for(let r=1;r<v.length;r++){const x=v[r],c=s_(x[2]),d=s_(x[1]);if(!c)continue;if(!out[c]||d>=out[c].asOf)out[c]={amount:n_(x[3]),asOf:d,note:s_(x[4])}}return out}
function readCardsFixed_(){const v=vals_(SHEETS.CARDS),cards={},fixed=[];for(let r=1;r<v.length;r++){const x=v[r],id=s_(x[0]),type=s_(x[1]);if(!id)continue;if(type==='카드'){cards[id]||={id,name:s_(x[4]),currency:s_(x[3]),active:s_(x[11])!=='종료',monthlyBills:{},balance:x[8]===''?null:n_(x[8]),dueDay:s_(x[9]),note:s_(x[12])};const m=month_(x[5]);if(m)cards[id].monthlyBills[m]=x[7]===''?null:n_(x[7]);if(x[8]!=='')cards[id].balance=n_(x[8])}else if(type==='고정비')fixed.push({id,name:s_(x[4]),currency:s_(x[3]),amount:n_(x[6]),active:s_(x[11])!=='종료',dueDay:s_(x[9]),note:s_(x[12])})}return{cardAccounts:Object.values(cards),fixedTemplates:fixed}}
function readSeed_(){const v=vals_(SHEETS.SEED),planStart=month_(v[1]&&v[1][1])||'2027-01',targetCurrency=s_(v[2]&&v[2][1])||'KRW',longGoal=n_(v[3]&&v[3][1]),rows=[],annualGoals={};for(let r=7;r<v.length;r++){const x=v[r],m=month_(x[0]);if(!m)continue;rows.push({month:m,target:n_(x[3]),actual:n_(x[4]),note:s_(x[11])});const y=m.slice(0,4);if(x[7]!==''&&x[7]!=null)annualGoals[y]=n_(x[7])}const y0=planStart.slice(0,4);if(!Object.keys(annualGoals).length&&v[4]&&v[4][1]!=='')annualGoals[y0]=n_(v[4][1]);return{planStart,targetCurrency,longGoal,annualGoal:n_(annualGoals[y0]),annualGoals,rows}}
function saveAll_(state){if(!state||!state.settings)throw new Error('state 필요');const lock=LockService.getScriptLock();lock.waitLock(15000);try{writeStart_(state.settings);writeLedger_(state.ledger||[]);writeSalaries_(state.salaries||[]);writeTemplates_(state.templates||[]);writeProjects_(state.projects||[]);writeSessions_(state.sessions||[],state.projects||[],state.fx||[]);writePayouts_(state.payouts||[],state.fx||[]);writeFx_(state.fx||[]);writeSeed_(state.seed||{});writeActual_(state.actualBalances||{});writeCardsFixed_(state);writeSettlements_(state.settlements||[]);SpreadsheetApp.flush();return bootstrap_()}finally{lock.releaseLock()}}
function writeStart_(settings){const s=sh_(SHEETS.FLOW),v=s.getDataRange().getValues(),m=settings.startMonth,b=settings.startBalances||{},seen={};for(let r=6;r<v.length;r++){if(month_(v[r][0])===m&&['JPY','KRW','USD'].includes(s_(v[r][1]))){const c=s_(v[r][1]);s.getRange(r+1,3).setValue(n_(b[c]));seen[c]=true}}if(Object.keys(seen).length<3)throw new Error('02 월간흐름에 시작월 '+m+' 3통화 행이 없습니다.')}
function writeLedger_(a){const rows=a.map(x=>[x.month||'',x.date||'',x.currency||'',x.category||'',x.item||'',n_(x.amount),x.reflect||'반영',x.status||'예정',x.workMonth||'',x.payMonth||x.month||'',x.linkId||'',x.memo||'',x.cashMode||'',x.settlementTarget||'']);setRows_(sh_(SHEETS.LEDGER),5,14,rows)}
function writeProjects_(a){setRows_(sh_(SHEETS.PROJECTS),2,12,a.map(x=>[x.id,x.name||'',x.platform||'',x.model||'단발',x.currency||'JPY',n_(x.unitPay),n_(x.failPay),n_(x.hourlyPay),n_(x.deductionRate),x.active===false?'종료':'활성',n_(x.delayDays),x.note||'']))}
function rate_(fx,m){return[...fx].filter(x=>x.month<=m).sort((a,b)=>a.month.localeCompare(b.month)).pop()||{id:'',krwPer100Jpy:0,jpyPerUsd:0}}
function toJpy_(v,c,m,fx){const r=rate_(fx,m);if(c==='JPY')return n_(v);if(c==='KRW'&&n_(r.krwPer100Jpy))return n_(v)/n_(r.krwPer100Jpy)*100;if(c==='USD'&&n_(r.jpyPerUsd))return n_(v)*n_(r.jpyPerUsd);return 0}
function writeSessions_(a,projects,fx){const pm={};projects.forEach(p=>pm[p.id]=p);const rows=a.map(x=>{const p=pm[x.projectId]||{},hours=n_(x.minutes)/60,gross=p.model==='시급'?hours*n_(p.hourlyPay):n_(x.pass)*n_(p.unitPay)+n_(x.fail)*n_(p.failPay),ded=gross*n_(p.deductionRate),net=gross-ded,m=month_(x.date),rt=rate_(fx,m);return[x.id,x.date||'',x.projectId||'',x.start||'',x.end||'',hours,n_(x.pass),n_(x.fail),n_(x.hold),n_(x.excluded),n_(x.pass)+n_(x.fail)+n_(x.hold)+n_(x.excluded),gross,ded,net,p.currency||x.currency||'',toJpy_(net,p.currency||x.currency||'',m,fx),rt.id||'',x.note||'']});setRows_(sh_(SHEETS.SESSIONS),2,18,rows)}
function writePayouts_(a,fx){setRows_(sh_(SHEETS.PAYOUTS),2,12,a.map(x=>[x.id,x.projectId||'',x.workMonth||'',x.payDate||'',x.payMonth||month_(x.payDate),x.currency||'',n_(x.expected),n_(x.actual),x.status||'입금예정',x.ledgerId||x.linkId||'',toJpy_(n_(x.actual)||n_(x.expected),x.currency,x.payMonth||month_(x.payDate),fx),x.memo||'']))}
function writeSalaries_(a){const rows=[];a.forEach(x=>(x.items||[]).forEach(i=>rows.push([x.id,x.payMonth||month_(x.payDate),x.workMonth||'',x.payDate||'',x.type||'급여',i.kind||'지급',i.name||'',n_(i.amount),n_(i.order),x.templateId||'',x.status||'예정',x.ledgerId||'',x.memo||'',new Date()])));setRows_(sh_(SHEETS.SALARY),2,14,rows)}
function writeTemplates_(a){const rows=[];a.forEach(x=>(x.items||[]).forEach(i=>rows.push([x.id,x.area||'MAIN',x.name||'템플릿',x.currency||'JPY',x.type||'급여',i.kind||'지급',i.name||'',n_(i.amount),'',x.active===false?'종료':'활성',n_(i.order),x.note||''])));setRows_(sh_(SHEETS.TEMPLATES),2,12,rows)}
function writeFx_(a){const rows=[],now=new Date();a.forEach(x=>{if(n_(x.krwPer100Jpy))rows.push([`fx-${x.month}-jpykrw`,x.month,'JPY','KRW',100,n_(x.krwPer100Jpy),'¥100 기준',now,x.note||'']);if(n_(x.jpyPerUsd))rows.push([`fx-${x.month}-usdjpy`,x.month,'USD','JPY',1,n_(x.jpyPerUsd),'$1 기준',now,x.note||''])});setRows_(sh_(SHEETS.FX),2,9,rows)}
function writeSeed_(seed){const sh=sh_(SHEETS.SEED),rows=[...(seed.rows||[])].sort((a,b)=>String(a.month).localeCompare(String(b.month))),annual=seed.annualGoals||{},actualStart=(rows.filter(x=>n_(x.actual)>0).map(x=>x.month).sort()[0]||''),startYear=(seed.planStart||'').slice(0,4);sh.getRange('B2').setValue(seed.planStart||'2027-01');sh.getRange('B3').setValue(seed.targetCurrency||'KRW');sh.getRange('B4').setValue(n_(seed.longGoal));sh.getRange('B5').setValue(n_(annual[startYear]||seed.annualGoal));sh.getRange('B6').setValue(actualStart);let ct=0,ca=0;const values=rows.map(x=>{ct+=n_(x.target);ca+=n_(x.actual);const y=x.month.slice(0,4);return[x.month,x.month>=(seed.planStart||'9999-99'),seed.targetCurrency||'KRW',n_(x.target),n_(x.actual),ct,ca,n_(annual[y]),n_(seed.longGoal),seed.planStart||'',actualStart,x.note||'']});setRows_(sh,8,12,values)}
function writeActual_(map){Object.keys(map).forEach(c=>saveActualBalance_({currency:c,amount:n_(map[c].amount),asOf:map[c].asOf,note:map[c].note||'사용자 확인'}))}
function saveActualBalance_(p){if(!p||!p.currency)throw new Error('currency 필요');const s=sh_(SHEETS.ACTUAL),v=s.getDataRange().getValues(),date=p.asOf||Utilities.formatDate(new Date(),Session.getScriptTimeZone()||'Asia/Tokyo','yyyy-MM-dd');for(let r=v.length-1;r>=1;r--){if(s_(v[r][2])===p.currency&&s_(v[r][1])===date){s.getRange(r+1,4,1,3).setValues([[n_(p.amount),p.note||'사용자 확인','아니오']]);return p}}s.getRange(s.getLastRow()+1,1,1,6).setValues([[`ACT-${date.replace(/-/g,'')}-${p.currency}`,date,p.currency,n_(p.amount),p.note||'사용자 확인','아니오']]);return p}
function writeCardsFixed_(state){const cards=state.cardAccounts||[],fixed=state.fixedTemplates||[],sets=state.settlements||[],rows=[];cards.forEach(c=>{const bills=c.monthlyBills||{},months=Object.keys(bills).sort();if(!months.length)rows.push([c.id,'카드',country_(c.currency),c.currency,c.name||'', '', '', '',c.balance==null?'':n_(c.balance),c.dueDay||'','카드청구포함',c.active===false?'종료':'활성',c.note||'']);else months.forEach((m,i)=>rows.push([c.id,'카드',country_(c.currency),c.currency,c.name||'',m,'',bills[m]==null?'':n_(bills[m]),i===months.length-1&&c.balance!=null?n_(c.balance):'',c.dueDay||'','카드청구포함',c.active===false?'종료':'활성',c.note||'']))});fixed.forEach(x=>rows.push([x.id,'고정비',country_(x.currency),x.currency,x.name||'','',n_(x.amount),'','',x.dueDay||'','고정비',x.active===false?'종료':'활성',x.note||'']));sets.forEach(x=>rows.push([x.id,x.id==='japan-revo'?'채무':'정산',country_(x.currency),x.currency,x.title||x.id,'','','',n_(x.current),'','상환·지원금',x.active===false?'종료':'활성','이번 계획 '+n_(x.planned)]));setRows_(sh_(SHEETS.CARDS),2,13,rows)}
function writeSettlements_(a){const jp=a.find(x=>x.id==='japan-revo')||{},kr=a.find(x=>x.id==='korea-support')||{},s=sh_(SHEETS.SETTLEMENT);s.getRange('B7').setValue(n_(jp.current));s.getRange('B8').setValue(n_(jp.planned));s.getRange('H7').setValue(n_(kr.current));s.getRange('H8').setValue(n_(kr.planned))}
